1.  int n=7;
    int c=__builtin_popcount(n); //this will return the count of set bits


2.  long long n=8765434521234567;
    int c=__builtin_popccountll(l); //this will return the count of set bits


3.  String a="123";
    a.sort(a.begin(),a.end()); //This ensures that the permutations generated by next_permutation are in lexicographical order.
    do{
      cout<<a;
    }while(next_permutation(a.begin(),a.end()); //This function rearranges the elements in the range [a.begin(), a.end()) to the next lexicographical permutation.
//If no such permutation exists (i.e., the string is in descending order), it resets the string to its smallest permutation (ascending order) and returns false.


4.  int maxel= *max_element(a.begin(),a.end()); //as max_element is works on iterator and also returns an iterator so need to derefence the value

